### ISSUE TITLE
Profiler

### ISSUE THREAD

**Issue by Aven02** [TeamSOC/SOCEngine#2]
개체의 프로파일러 구현.
성빈이는 이거 읽으면 알아서 구현할거 여기에 적고 수정 바람

**Comment by Jin02** [comment]
쉐이더 부분은 어느정도 다 구현한 것 같다.
문제는 구조가 엉킨게 많아 GI관련 cpp 코드를 전부 새로 짜야한다.

**Comment by Jin02** [comment]
디버깅을 하려고 하면..
그래픽 드라이버가 응답 없음 상태로 전환되고 컴퓨터가 다운되서 진행이 많이 힘들다..

어떤 문제인지는 딱히 잘 모르겠다 -_-..

**Comment by Jin02** [comment]
~~현재 컴퓨터 사양이 생각보다 넉넉하다보니 복셀화부터 6방향 복셀을 사용해도 괜찮겠다 싶었는데, 직접 구현해보니 많이 버겁다.~~

~~이것 저것 테스트를 하려고 하면 GPU 메모리 없다고 에러가 나와서 그냥 방향이고 뭐고 복셀 하나로 처리해야한다.~~
-> 256^3 크기의 복셀맵에서 생긴 문제인데, 디버깅할때는 128^3로 크기를 잡으면 된다. 물론 256은 Voxel Viewer를 포기해야한다.

그러니까.. 지금 까지 구현한 모든 것들을 다시 뜯어야한다.
6방향 처리하는 건 Injection단계에서 처리하던가 해야할 듯 싶다.

---

~~ 추가~~
~~1. 6방향 처리는 Mipmap 단계에서 하면 될 듯 싶다.~~
~~비슷한 효과를 충분히 얻을 수 있을 듯 싶다. 물론, Cascade 단계가 올라갈 수록 쓸모 없겠지만..
뭐, 그래도 메모리를 엄청나게 아끼는데 뭐 어떤가~~

그냥 Injection 단계에서 처리했다

##

**Comment by Jin02** [comment]
![AlbedoTest](http://i.imgur.com/TCp493h.png)
Albedo Test

![NormalTest](http://i.imgur.com/PlsxsJ4.png)
Normal Test

![InjectionTest](http://i.imgur.com/NJX7Yoj.png)
Injection Test

버그를 잡기 위해 복셀들을 모두 시각화처리를 하였다.

**Comment by Jin02** [comment]
![AnisotropicInjection](http://i.imgur.com/a7nqAKJ.png)
Anisotropic Injection Test

![AnisotropicMipmap](http://i.imgur.com/IcoHIGD.png)
Mipmap Test

다시 6면을 사용했다 -_-..
대신 GPU 메모리 문제로 인해 최대 해상도가 128x128x128 이 한계이다.
그림자를 제외하고 드문 드문 검은색으로 복셀이 칠해져 있는 부분이 있는데 이건 Bloating 처리를 해야 해결 될 문제일 듯 싶다.

그나저나 확실히 시각화 처리를 하니까 버그잡기가 정말 수월하구나..

**Comment by Jin02** [comment]
![DiffuseTest](http://i.imgur.com/GexTTDw.png)
ddiffuse 테스트

indirect diffuse만 출력한 상태이다.
아직 썩.. 결과물이 맘에 들진 않는다

## 

해상도를 낮춰서 테스트하고 있는데 그래픽 카드가 계속 부들부들거려서 불안하다;
소음 소리만 들어봐도 비행기가 곧 이륙할거 같다

**Comment by Jin02** [comment]
InterlockedCompareExchange 이게 문제가 있는 것 같다.
뭐, 그거 뿐만이 아니더라도 현재 구현된 StoreVoxelMapAtomicColor들은 전부 제대로 돌아가지 않는 상태이다.

GL4의 imageAtomicCompSwap같은 효과를 가진 기능을 찾아야 하는데 보이지가 않는다..

**Comment by Jin02** [comment]
![Metallic3](http://i.imgur.com/ubOO83n.png)

현재 개발 환경에 사용중인 놋북이 5~6년전에 발매되었고, 그래픽 드라이버 업데이트가 불가능해서, Interlocked 관련 기능이 제대로 굴러가리란 보장을 못하겠다.

특히 매 프레임마다 복셀화 처리 및 인젝션 처리를 하려고 하니,
뭔가 제대로 계산이 되지 않는지 위의 사진에서 보이지도 않는 알 수 없는 색이(주로 파란색)이 섞여서 나오거나 화면이 자주 깜빡거렸다. 간헐적으로 그래픽 카드 다운되서 화면이 나가는건 덤;

그래서 그냥 VCT까지 단 한 프레임만 렌더링하고 했더니 위처럼 어느 정도 잘뜬다..
후......

위의 사진은 metallic 0.3에 diffuse만 되어 있는 모습이다.
그림자는 underScaneSize를 변경해줘야 하는데 귀찮다.

**Comment by Jin02** [comment]
![roughnesshigh](http://i.imgur.com/qjBXsu2.png)
Roughness가 높을 때

![roughnesslow](http://i.imgur.com/gS8Uqp2.png)
Roughness가 낮을 때

뭐.. Specular는 glossy하게 이런식으로 나온다.
Roughness가 높을 때 나오는 푸른색은 위의 코멘트와 같이 이유를 전혀 알 수 없다.
걍 하드웨어 에러겠지 -_- 논리적으로도 수식적으로도 저게 뜰리가 없는데 뜬다는거면..

이제 이거랑 diffuse랑 잘 섞으면 될 것 같다..

**Comment by Jin02** [comment]
![Metallic03](http://i.imgur.com/T480Sy1.png)
Diffuse + Specular, Metallic이 0.7일때의 모습.

음.. 괜찮게 된게 맞긴 한가?

**Comment by Jin02** [comment]
uav를 이용하여 텍스쳐 atomic 연산을 처리할 때, while과 for는 정상적으로 작동이 되지 않는다.
이유는 모르겠다.

do-while이 그나마 어느정도 작동은 하는 것 같다만, 이것도 정상적으로 잘 작동하진 않는다.
그러니깐, 값이 너무 가끔씩 들어간다. 모든 값이 전부 계산되지 않는다고 생각하면 된다.

답답한게, 구글링해봐도 나만 그런게 아니고 여러 사람들이 드문드문 겪는 문제인듯하다.
뭐 누군 do-while이 안되고 while이 되지만 둘 다 되는 사람도 있고.. 뭐 답이 없다. 그래픽카드 문제라니;

그리고 난 왜 둘 다 안되는건가..
후 -_-..

**Comment by Jin02** [comment]
![WTF](http://i.imgur.com/D10RQMR.png)
위의 사진은 https://github.com/Jin02/SOCEngine/blob/%232/SOCEngine/SOCEngine/ShaderCodes/GICommon.h#L100 에서 StoreVoxelMapAtomicColorAvgNibble을 Voxelization에서 사용한 모습. Metallic은 0.9이다. 뒤의 반사되는 모습을 본다면 위의 모습보다 훨씬 정확한 결과물이다. 그런데 정작 작성해서 사용하고 있는 함수는 정상이 아니라서.. 문제가 된다.

StoreVoxelMapAtomicColorAvgNibble의 모습을 보면 알겠지만, 이건 정상적으로 작동하는 함수가 아니다. 근데 결과물은 가장 제대로 뜬다 -_-..

atomic연산을 하지 않고 복셀 텍스쳐에 값을 직접넣어도 잘 작동이 안되고,
StoreVoxelMapAtomicColorAvg를 사용해도 잘 작동이 되지 않는게 왜 Nibble에서는 되는건지 모르겠다.

이제는 개발환경을 바꿔봐야하나 싶다..
뭐.. gt540m에 그래픽 드라이버 업데이트가 불가능한 환경이니(업데이트하면 드라이버가 인식을 못함) 이런 버그가 뜨는게 당연하다고 생각해야나..

그냥 다 포기하고 GL을 선택하고 싶어도 현재 개발환경이 GL4를 지원하지 않는다.

**Comment by Jin02** [comment]
#7 에 남은 이슈들이 있다.

**Comment by Jin02** [comment]
This issue was moved to TeamSOC/SOCEngine#3
