### ISSUE TITLE
어플리케이션 레벨 구현

### ISSUE THREAD

**Issue by Aven02** [TeamSOC/SOCEngine#3]
플랫폼 종속적인 부분의 구현을 엔진에서 분리하여 구현

이미 잘 알게 된 부분일 것이라고 생각됨

**Comment by Jin02** [comment]
GPU Gem 3에 있는 Summed Area VSM를 참고

**Comment by Jin02** [comment]
이전
![ShadowMapping](http://i.imgur.com/KczmdCc.png)

현재
![VSM](http://i.imgur.com/3NYNdy0.png)

## 

inverted depth일때와, 그렇지 않을때와 구현 방식을 약간씩 다르게해서 조금 오래걸렸다.
그리고 좀 다른 프로젝트 구상 및 테스트 중이여서 늦었다 ㅜㅜ..

보통때라면 그냥 Shadow Map을 그릴때 z를 뒤집어서 사용하지 않고 그냥 했겠다만..
#2 와 연관되어 뒤집어진 float의 정확도가 필요해서 이렇게 구현할 수 밖에 없었다.
나중에 #2 가 완성되면 Inverted Depth일때와 아닐때와 비교하고 적당히 괜찮은 걸 고른 후 나머지는 지울 생각이다.

뭐 여튼 기본적인 VSM은 구현했다.

Summed Area는.. 심심할때 조금씩 하면 될 것 같다.
자료도 많으니 급하게 안해도 된다.

**Comment by Jin02** [comment]
Point Light Shadow랑 관련된 문제인지, 아니면 VSM 자체의 문제인지는 몰라도 그림자가 상당히 깨진다.

**Comment by Jin02** [comment]
1. SAVSM 까진 안함
2. Bleeding 문제

**Comment by Jin02** [comment]
![noise](http://i.imgur.com/JGmsV8E.png)
Spot Light 테스트..
알 수 없는 버그가 아주 신나게 펑펑 터진다.
bias나 moment 작성 관련되서 생기는 버그 인거 같긴한데 어떻게 해결해야할지 감을 잡을 수가 없다.

**Comment by Jin02** [comment]
http://lab.gamecodi.com/board/zboard.php?id=GAMECODILAB_QnA_etc&page=1&sn1=&divpage=1&sn=off&ss=on&sc=on&select_arrange=last_comment&desc=desc&no=4003

새벽에 질문 올려서 매우 빠르게 답변을 받았다.
하.. 살것 같다

생각없이 예전에 texture address mode를 wrap으로 작성한 linearState를 사용했던게 버그의 원인이였다.
아래는 수정한 vsm 결과물
![result](http://i.imgur.com/TgLsvMj.png)

**Comment by Jin02** [comment]
수정된 코드는 #5 에 있다.
#5 branch로 가면 된다.

**Comment by Jin02** [comment]
This issue was moved to TeamSOC/SOCEngine#4
